export enum Routes {
  Signin = 'SigninScreen',
  HomeScreen = 'HomeScreen',
  HomeDrawer = 'HomeDrawer',
  Video = 'Video',
  EditScreen = 'EditScreen',
  ProfileScreen = 'ProfileScreen',
  TabNavigation = 'TabNavigation',
  Home = 'Home',
  Add = 'Add',
  Profile = 'Profile',
  VideoPlayer = 'VideoPlayer',
  VideoList = 'VideoList',
  Stack = 'Stack',
  Drawer = 'Drawer',
  Setting = 'Setting',
  TnC = 'TermsAndCondition',
  ResetPassword = 'ResetPassword',
  NotificationScreen = 'NotificationScreen',
  UserDetails = 'UserDetails',
}
