export const ScreenStrings = {
  signin: 'Signin',
  register: 'Register',
  newAccount: 'New to Clipzer?',
  forgorPassword: 'Forgot Password?',
  or: 'OR',
  googleSignin: 'Signin with Google',
  email: 'email',
  password: 'Password',
  failed: 'Invalid Credentials!',
  failureDetail: 'Please Enter the Correct Details.',
  home: 'Home',
  add: 'Add',
  profile: 'Profile',
  video: 'Video',
  mail: 'Email',
  firstname: 'First Name',
  lastname: 'Last Name',
  edit: 'Edit',
  saveChanges: 'Save Changes',
  alert: 'Changes Saved',
  takePicture: 'Take Picture',
  upload: 'Upload From Gallery',
  profilePicture: 'View Profile Picture',
  error: 'Error',
  errorMessage: 'Profile is not updated ! Try Again.',
  newUser: 'User Added',
  noImage: "You haven't updated your profile!",
  addUser: 'Add a New User',
  hold: 'Hold On!',
  noProfile: "You haven't updated you profile..",
  addProfile: 'Add Profile',
  skip: 'Skip',
  userAdded: 'User Added',
  version: 'v1.0.0',
  setting: 'Setting',
  subscribe: 'Subscribe',
  signout: 'SignOut',
  subscribers: '100K',
  share: 'Share',
  report: 'Report',
  chat: 'Chat',
  comment: 'Comments',
  Setting: 'Setting',
  ok: 'OK',
  myProfile: 'My Profile',
  account: 'Your Account',
  passwordChange: 'Change Password',
  theme: 'Theme',
  changeTheme: 'Change Theme',
  moreInfo: 'More Info And Support',
  policy: 'Privacy Policy',
  terms: 'Terms and Condition',
  light: 'Bright as Sun',
  dark: 'Dark as Night',
  default: 'System Default',
  new: 'IS_FIRST',
  isdefault: 'IsDefault',
  textDefault: 'default',
  regulations: 'Regulations',
  updatePassword: 'Update Password',
  incorrectPassword: 'Incorrect Password!',
  passwordUpdated: 'Password Updated!',
  notification: 'Notification',
  noNotify: 'Uhhh Ohhhhh!',
  noNotificationPresent: 'Seems no notification is present!',
  details: 'Details',
  follow: 'Follow',
  following: 'Following',
  readMore: '... Read More'
};

export const PlaceholderStrings = {
  email: 'Email ID',
  Password: 'Password',
  search: 'What are you looking for?',
  newPassword: 'New Password',
  reenterPassword: 'Reenter Password',
};

export const ValidationStrings = Object.freeze({
  required: 'It is a required field',
  invalidemail: 'Invalid Email',
  minLength: 'Minimum 8 characters required',
  noMatch: 'Password do not match',
});
